### PR TITLE
Add the option to pass function as tags

### PR DESCRIPTION
**Pull request by reactormonk**
I came across cbor data which had negative tags, so passing an array doesn't work as well anymore.

### CODE REVIEW

**Comment by rvagg** [comment]
Are you sure it's valid data? It shouldn't be possible to get a negative tag:

> Major type 6:
> A tagged data item ("tag") whose tag number, an integer in the range 0..264-1 inclusive, is the argument and whose enclosed data item (tag content) is the single encoded data item that follows the head. See Section 3.4.

(https://www.rfc-editor.org/rfc/rfc8949.html#section-3.1)

Even negative numbers are encoded as positive but have a major type that says to flip them negative when decoding them. So it's not even technically possible to encode a negative number in this field unless you're reading it as a negative.

Maybe cborg is at fault here? Is it telling you that it has a tag number that's negative? If so, then I should have a look at that, maybe it's out of range for naïve decoding within the easy JavaScript number range and it needs to be more careful. Maybe you could share a sample of the data? (also for fun, try passing it through the CLI to see what it supposedly contains: https://github.com/rvagg/cborg#cborg-hex2diag-hex-string - there's also a `bin2diag` command that'll read raw binary, but I obviously haven't updated the README to match all the new CLI options I recently added).

**Comment by reactormonk** [comment]
The specification of the data explicitly mentions the claim key to be negative: https://github.com/ehn-dcc-development/hcert-spec/blob/main/hcert_spec.md#33-cwt-claims

It explicitly has `negint` in it, so I guess that's the flag you're talking about?

```
  39 0103                                         #   negint(-260)
  a1                                              #   map(1)
    01                                            #     uint(1)
    a4                                            #     map(4)
```

And I find the function passing interface to be more ergonomic in general as well ;-)

**Comment by rvagg** [comment]
OK, but that's not a major type 6, it's a major type 1 (negint) followed by a 5 (map), so major 6 (tag) doesn't come in to play here at all so you shouldn't need to be futzing with the tag handling at all in this position should you?

I haven't read the CWT spec before, but it does talk about tags in the standard way: https://datatracker.ietf.org/doc/html/rfc8392#section-5, CWT tag being 61 and the various COSE tags that are mentioned in the tag registry: https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml - but that seems to be all about whether you want to encapsulate CWT within a larger chunk of CBOR and absolutely needed to disambiguate it:

> Its [the CWT tag] use is optional and is intended for use in cases in which this information would not otherwise be known.

Other than that, CWT only seems to need tags for some values where you need to reach for dates and whatnot.

So I'm not entirely opposed to this change, but I'm not seeing a justification for it in your data or the CWT spec. Do you have larger chunks of data that demonstrate breakage here that I can help fix?

**Comment by reactormonk** [comment]
It's not about the data in the CWT spec, it's part of the data that's contained inside the CWT. That's on a negative tag. Sadly I haven't found any sample data, and I don't really wanna post my vaccine certificate online.

**Comment by rvagg** [comment]
I think you might be mixing up "tag" with "major" and even "value". Tag has a very specific meaning in CBOR and can only be a positive integer. Your negative values in CWT are something else entirely, they're values in the decoded form.

**Pull request closed without merging**
